import { useState, useEffect } from 'react'
import axios from 'axios'
import Note from './components/Note'
import Footer from './components/Footer'
import noteService from './services/notes'
import Notification from './components/Notification'
// React uses the key attributes of objects in an array
// to determine how to update the view generated by a
// component when the component is re-rendered.
// map always creates a new array,

// Quite often the root of the problem is that the props
// are expected to be of a different type, or called with a
//different name than they actually have, and destructuring
// fails as a result.

//we must never mutate state directly in React!


const App = (props) => {

  const [notes,setNotes] = useState([])
  const [newNote, setNewNote] = useState('a new note...')
  const [showAll, setShowAll] = useState(true)
  const [errorMessage, setErrorMessage]= useState(null)

  useEffect( () => {
    console.log('effect')

    noteService
    .getAll()
    .then(initialNotes =>{
      setNotes(initialNotes)
    })
  },[])

  console.log('render', notes.length, 'notes')

  const addNote = (event) =>{
    event.preventDefault()
    const noteObject = {
    content: newNote,
    important: Math.random() < 0.5,
   // id: String(notes.length + 1), ommitted this one
  }
 noteService
 .create(noteObject)
 .then(returnNote => {
  setNotes(notes.concat(returnNote))
  setNewNote('')
 })
 }

    const handleNoteChange = (event) => { // This event handler is called every time a change occurs in the input element
    console.log(event.target.value)
    setNewNote (event.target.value)
    // we did not need to call the event.preventDefault()
    //because no default action occurs on an input change
    }

   const notesToShow = showAll
    ? notes
    : notes.filter(note => note.important)


    const toggleImportanceOf = (id) => {
    const url = `http://localhost:3001/api/notes/${id}` // find url of note to modify
    const note = notes.find( n => n.id === id) // find note to modify
    const changedNote = {...note, important: !note.important} // create a copy  and  the property modified

    noteService
    .update(id, changedNote)  //  change the server with the  changednote
    .then(returnNote => {  // then  change the array in state to render again
      setNotes((notes.map(note => note.id === id ? returnNote : note)))
    })// create a copy of the original array and replace the   note of the id with the  response.data
    .catch(error => {
      setErrorMessage(`Note '${note.content}' was already removed from server`)
       setTimeout(() => {
          setErrorMessage(null)
        }, 5000)
      setNotes(notes.filter(n => n.id !== id)) // to keep state updated with the server in case note was deleted from server
    })

    }

  return (
    <div>
      <h1>Notes</h1>
      <Notification  message={errorMessage}/>
      <div>
        <button onClick={() => setShowAll(!showAll)}>
          show {showAll ? 'important' : 'all'}
        </button>
      </div>
      <ul>
        {notesToShow.map(note =>
          <Note  key= {note.id} note={note} toggleImportance={() => toggleImportanceOf(note.id)}/>
        )}
      </ul>
      <form onSubmit={addNote}>
        <input value ={newNote} onChange ={handleNoteChange}/>
        <button type='submit'>save note</button>
      </form>
      <Footer />
    </div>
  )
}

export default App
