### Get all notes
GET http://localhost:3001/api/notes


### Get one note
GET http://localhost:3001/api/notes/69cae7a8987313708ec83c3f


### Delete note
DELETE http://localhost:3001/api/notes/69d6af617551c45f8b4673e2
